### ISSUE TITLE
DEF related inconsisence

### ISSUE THREAD

**Issue by starsareintherose** [WA6YDQ/dbasic#1]
Hello

Thanks for the great code, however, I found some inconsistency based on original manual https://www.dartmouth.edu/basicfifty/basicmanual_1964.pdf

`DEF` should be

```
DEF FNC(G) = G^3 + 2.7*G
```

instead of 

```
def fnf 1/(2*3.1415*(sqr(l*c)))
```

**Comment by WA6YDQ** [comment]
Yep. For some reason I got lazy writing that bit of code and went with the old microsoft basic definition of a function instead of the Dartmouth version. Must have been a late night.

If it's a quick fix I'll have a look at it in a few days.

**Comment by WA6YDQ** [comment]
Updated: The dartmouth basic reference I used when writing this program was the earliest available (and at the time, all I could find). Since then, later specifications became available and show a much different basic interpreter. The original seems to have been a pre-release. Anyway, I based this program on that.

Later documents show larger variables, matricies, etc, which aren't present in this code. As such, this program doesn't represent the later dartmouth basic interpreter. For now, consider this as just another version of basic. If you're looking for an original dartmouth basic, you will need to keep looking.


Original:
As pointed out in the readme's and example code, this program has a few inconsistencies with the original dartmouth version. As such, since the def command does work as stated, I'm going to leave it as is. 
If you are running original source code, making a small change hopefully won't be too much of a burden.
